import { createHash } from 'node:crypto';
import {
  copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { sanitizeMemoryText, renderSharedMemory, validateSharedMemory } from '../hooks/memory-schema.mjs';
import {
  enqueueMemoryEvent, projectMemoryOutbox, repairMemoryLedger,
} from '../hooks/memory-store.mjs';
import { writeFileAtomic } from '../hooks/session-note-io.mjs';
import { validateMemoryBundle } from './validate-memory.mjs';
import { checkMemoryBundle } from '../hooks/vault-health.mjs';

const BRAIN = '.brain';
const LEDGER = 'MEMORY_EVENTS.jsonl';
const SHARED = 'SHARED_MEMORY.md';
const CANDIDATES = 'MEMORY_CANDIDATES.jsonl';

function brainPath(vault, name) { return join(vault, BRAIN, name); }
function hash(value) { return createHash('sha256').update(String(value)).digest('hex'); }

function projectId(vault) {
  const marker = JSON.parse(readFileSync(brainPath(vault, 'PROJECT.json'), 'utf8'));
  if (!marker?.projectId) throw new Error('PROJECT.json inválido: projectId ausente.');
  return marker.projectId;
}

function legacyCandidates(content) {
  const safe = sanitizeMemoryText(content).replace(/\r\n/g, '\n');
  const candidates = [];
  let section = 'Legacy';
  for (const line of safe.split('\n')) {
    const heading = line.match(/^#{1,3}\s+(.+)/);
    if (heading) { section = heading[1].trim(); continue; }
    const value = line.replace(/^[-*]\s+/, '').trim();
    if (!value) continue;
    const candidateId = `legacy-${hash(`${section}\0${value}`).slice(0, 16)}`;
    candidates.push({
      v: 1,
      candidate_id: candidateId,
      reason: 'legacy_shared',
      memory_key: `legacy.${hash(section).slice(0, 8)}.${candidates.length + 1}`,
      value,
      section: sanitizeMemoryText(section),
      source: 'SHARED_MEMORY.md',
    });
  }
  return candidates;
}

function candidateText(candidates) {
  return candidates.map((item) => `${JSON.stringify(item)}\n`).join('');
}

export function seedMemoryV2(vault) {
  const brain = join(vault, BRAIN);
  mkdirSync(brain, { recursive: true });
  const created = [];
  const artifacts = [
    [LEDGER, ''],
    [CANDIDATES, ''],
    [SHARED, renderSharedMemory()],
  ];
  for (const [name, content] of artifacts) {
    const path = join(brain, name);
    if (!existsSync(path)) {
      writeFileSync(path, content, 'utf8');
      created.push(name);
    }
  }
  return { status: created.length ? 'seeded' : 'unchanged', created };
}

export function memoryStatus(vault) {
  return checkMemoryBundle(vault);
}

export function migrateMemory(vault, { apply = false } = {}) {
  projectId(vault);
  const sharedPath = brainPath(vault, SHARED);
  const hadShared = existsSync(sharedPath);
  const legacy = hadShared ? readFileSync(sharedPath, 'utf8') : '';
  const parsed = validateSharedMemory(legacy);
  const alreadyV2 = parsed.ok && parsed.metadata.schema_version === 2;
  const candidates = alreadyV2 ? [] : legacyCandidates(legacy);
  const backupPath = hadShared ? `${sharedPath}.legacy-${hash(legacy).slice(0, 12)}.bak` : null;
  if (!apply) return { status: 'dry-run', alreadyV2, candidates: candidates.length, backupPath };
  if (alreadyV2) {
    seedMemoryV2(vault);
    return { status: 'unchanged', alreadyV2: true, candidates: 0, backupPath: null };
  }

  // Validate every generated byte before the first publication. CORE is never written.
  const emptyShared = renderSharedMemory();
  const sharedValidation = validateSharedMemory(emptyShared, { eventIds: new Set() });
  if (!sharedValidation.ok) throw new Error(`Migração inválida: ${sharedValidation.errors.join(' ')}`);
  if (backupPath && !existsSync(backupPath)) copyFileSync(sharedPath, backupPath);
  if (!existsSync(brainPath(vault, LEDGER))) writeFileAtomic(brainPath(vault, LEDGER), '');
  writeFileAtomic(sharedPath, emptyShared);
  writeFileAtomic(brainPath(vault, CANDIDATES), candidateText(candidates));
  const validation = validateMemoryBundle(vault);
  if (!validation.ok) throw new Error(`Bundle migrado inválido: ${validation.errors.join(' ')}`);
  return { status: 'migrated', alreadyV2: false, candidates: candidates.length, backupPath, validation };
}

function readCandidates(vault) {
  const path = brainPath(vault, CANDIDATES);
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8').split('\n').filter(Boolean).map((line) => JSON.parse(line));
}

export function decideMemoryCandidate(vault, { action, candidateId, value } = {}) {
  if (!['promote', 'reject'].includes(action)) throw new TypeError('action deve ser promote ou reject.');
  if (!candidateId) throw new TypeError('candidateId é obrigatório.');
  const candidates = readCandidates(vault);
  const candidate = candidates.find((item) => item.candidate_id === candidateId);
  if (!candidate) throw new Error(`Candidate não encontrado: ${candidateId}`);
  const now = new Date().toISOString();
  const event = {
    v: 1,
    event_id: `cli-${action}-${hash(candidateId).slice(0, 20)}`,
    project_id: projectId(vault),
    memory_key: action === 'promote' ? candidate.memory_key : `candidate.rejected.${candidateId}`,
    operation: 'assert',
    value: sanitizeMemoryText(action === 'promote' ? (value ?? candidate.value ?? candidate.values?.[0] ?? '') : 'rejected'),
    authority: 'verified',
    activation_id: 'wendkeep-memory-cli',
    turn_sequence: 0,
    observed_at: now,
    evidence: [`candidate:${candidateId}`],
  };
  enqueueMemoryEvent(vault, event);
  const projection = projectMemoryOutbox(vault);
  if (projection.status === 'busy') return { status: 'busy', candidateId };
  const remaining = candidates.filter((item) => item.candidate_id !== candidateId);
  const projected = readCandidates(vault);
  const merged = new Map([...remaining, ...projected].map((item) => [item.candidate_id, item]));
  writeFileAtomic(brainPath(vault, CANDIDATES), candidateText([...merged.values()]));
  return { status: action === 'promote' ? 'promoted' : 'rejected', candidateId, eventId: event.event_id, projection };
}

export function repairMemory(vault) {
  const repaired = repairMemoryLedger(vault);
  if (repaired.status === 'busy') return repaired;
  const projection = projectMemoryOutbox(vault);
  return { status: projection.status === 'busy' ? 'busy' : 'repaired', repaired, projection };
}

export function runValidateMemoryBundle(argv) {
  const vault = option(argv, '--vault');
  if (!vault) {
    process.stderr.write('wendkeep validate-memory: --vault requer um path.\n');
    process.exitCode = 2;
    return;
  }
  if (!existsSync(vault)) {
    process.stderr.write(`wendkeep validate-memory: not found: ${vault}\n`);
    process.exitCode = 2;
    return;
  }
  const result = validateMemoryBundle(vault);
  if (!result.ok) {
    process.stderr.write(`❌  bundle de memória inválido (${result.errors.length} erro(s)):\n`);
    for (const error of result.errors) process.stderr.write(`   - ${error}\n`);
    process.exitCode = 1;
    return;
  }
  process.stdout.write('✅  bundle de memória v2 OK (CORE + ledger + SHARED).\n');
  process.exitCode = 0;
}

function option(argv, name) {
  const index = argv.indexOf(name);
  if (index >= 0) return argv[index + 1] || '';
  return argv.find((item) => item.startsWith(`${name}=`))?.slice(name.length + 1) || '';
}

export function runMemory(argv) {
  const [sub, positional] = argv;
  const vault = option(argv, '--vault') || process.env.OBSIDIAN_VAULT_PATH;
  if (!vault) { process.stderr.write('wendkeep memory: passe --vault <path>.\n'); process.exitCode = 2; return; }
  try {
    let result;
    if (sub === 'status') result = memoryStatus(vault);
    else if (sub === 'migrate') result = migrateMemory(vault, { apply: argv.includes('--apply') });
    else if (sub === 'repair') result = repairMemory(vault);
    else if (sub === 'promote' || sub === 'reject') result = decideMemoryCandidate(vault, { action: sub, candidateId: positional });
    else { process.stderr.write('wendkeep memory: use status | migrate [--apply] | repair | promote <candidate> | reject <candidate>.\n'); process.exitCode = 2; return; }
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    process.exitCode = sub === 'status' && argv.includes('--gate')
      ? (result.status === 'blocked' ? 1 : 0)
      : (result.ok === false ? 1 : 0);
  } catch (error) {
    process.stderr.write(`wendkeep memory: ${error.message}\n`);
    process.exitCode = 1;
  }
}
