// Vault color system for `wendkeep init`. Generated CSS snippet (ported from the
// NutriGym-Vision design) plus Obsidian graph color groups. Two visual layers:
//   - file explorer: each taxonomy folder gets an accent (border + dot + hover)
//   - open note: colored by its `cssclasses` (topic-session/decision/bug/learning)
//     via a --note-accent var driving headings, strong, tags, tables, blockquotes
// Folder/topic lists are derived from maps that mirror the vault taxonomy, so the
// snippet stays in sync. Pure + side-effect free; init does the file I/O.

export const SNIPPET_NAME = 'wendkeep-colors';

// Readable line width for note content — Obsidian's default (~700px) wastes wide monitors.
// Ajuste aqui (1200px / 1400px / 100vw) para mudar em todos os vaults de uma vez.
export const READABLE_LINE_WIDTH = '1400px';

import { LOCALES } from '../hooks/locale.mjs';
const PT = LOCALES['pt-BR'];

// Base palette (hex + "r, g, b" for rgba()).
const PALETTE = {
  blue: { hex: '#2f80ed', rgb: '47, 128, 237' },
  violet: { hex: '#8f5cf7', rgb: '143, 92, 247' },
  red: { hex: '#e03131', rgb: '224, 49, 49' },
  green: { hex: '#2f9e44', rgb: '47, 158, 68' },
  amber: { hex: '#f59f00', rgb: '245, 159, 0' },
  teal: { hex: '#0ca678', rgb: '12, 166, 120' },
  indigo: { hex: '#4263eb', rgb: '66, 99, 235' },
  slate: { hex: '#64748b', rgb: '100, 116, 139' },
};

// File-explorer folder KEY -> palette key; folder names resolve via the vault locale.
const PALETTE_BY_KEY = {
  inbox: 'amber',
  project: 'indigo',
  sessions: 'blue',
  linear: 'teal',
  decisions: 'violet',
  bugs: 'red',
  learnings: 'green',
  specs: 'teal',
  changes: 'amber',
};
function folderPalette(loc) {
  return [...Object.entries(PALETTE_BY_KEY).map(([k, p]) => [loc.folders[k], p]), ['Templates', 'slate']];
}

// Note cssclass -> palette + locale folder key; `folder` resolves per locale.
const NOTE_TYPES = {
  session: { cssClass: 'topic-session', folderKey: 'sessions', palette: 'blue' },
  decision: { cssClass: 'topic-decision', folderKey: 'decisions', palette: 'violet' },
  bug: { cssClass: 'topic-bug', folderKey: 'bugs', palette: 'red' },
  learning: { cssClass: 'topic-learning', folderKey: 'learnings', palette: 'green' },
  spec: { cssClass: 'topic-spec', folderKey: 'specs', palette: 'teal' },
  change: { cssClass: 'topic-change', folderKey: 'changes', palette: 'amber' },
};
// Legacy pt-shaped export (folder names resolved at pt-BR) kept for compat.
export const NOTE_COLORS = Object.fromEntries(
  Object.entries(NOTE_TYPES).map(([k, v]) => [k, { cssClass: v.cssClass, folder: PT.folders[v.folderKey], palette: v.palette }]),
);

// cssclasses that get the note-accent treatment (the note types + a home note).
const TOPIC_CLASSES = [...Object.values(NOTE_TYPES).map((n) => n.cssClass), 'vault-home'];
const NOTE_ACCENTS = [
  ...Object.values(NOTE_TYPES).map((n) => ({ cssClass: n.cssClass, palette: n.palette })),
  { cssClass: 'vault-home', palette: 'indigo' },
];

const FX = '.workspace-leaf-content[data-type="file-explorer"] .nav-folder-title';
const topicReading = TOPIC_CLASSES.map((c) => `.${c}`).join(', ');

export function renderColorSnippetCss(loc = PT) {
  const FOLDER_PALETTE = folderPalette(loc);
  const folderSel = FOLDER_PALETTE.map(([f]) => `[data-path^="${f}"]`).join(',\n  ');
  const rootVars = Object.entries(PALETTE)
    .map(([k, v]) => `  --us-${k}: ${v.hex};\n  --us-${k}-rgb: ${v.rgb};`)
    .join('\n');

  const folderAccentVars = FOLDER_PALETTE.map(([folder, key]) =>
    `${FX}[data-path^="${folder}"] {\n  --folder-accent: var(--us-${key});\n  --folder-accent-rgb: var(--us-${key}-rgb);\n}`,
  ).join('\n\n');

  const noteAccentVars = NOTE_ACCENTS.map(({ cssClass, palette }) =>
    `.markdown-preview-view.${cssClass},\n.markdown-source-view.${cssClass} {\n  --note-accent: var(--us-${palette});\n  --note-accent-rgb: var(--us-${palette}-rgb);\n}`,
  ).join('\n\n');

  return `/* ${SNIPPET_NAME} — generated by wendkeep. File-explorer + note-type colors. */
:root {
${rootVars}
}

.theme-dark { --us-line-tint: 44%; }
.theme-light { --us-line-tint: 36%; }

/* --- Readable line width: wider than Obsidian's ~700px default ------------ */
/* !important porque o Obsidian declara --file-line-width com specificity alta; sem ele
   a regra do body não vence e a linha volta pro ~700px. */
body {
  --file-line-width: ${READABLE_LINE_WIDTH} !important;
}

/* --- File explorer: accented folders ------------------------------------- */
${FX} {
  border-left: 3px solid transparent;
  border-radius: 0 6px 6px 0;
  margin: 1px 4px 1px 0;
  transition: background-color 120ms ease, border-color 120ms ease, color 120ms ease;
}

${folderAccentVars}

${FX}:is(
  ${folderSel}
) {
  border-left-color: var(--folder-accent);
  color: color-mix(in srgb, var(--folder-accent) var(--us-line-tint), var(--text-normal));
}

${FX}:is(
  ${folderSel}
):hover {
  background-color: rgba(var(--folder-accent-rgb), 0.13);
}

${FX}:is(
  ${folderSel}
) .nav-folder-title-content::before {
  content: "";
  display: inline-block;
  width: 0.58em;
  height: 0.58em;
  margin-right: 0.48em;
  border-radius: 999px;
  background: var(--folder-accent);
  box-shadow: 0 0 0 3px rgba(var(--folder-accent-rgb), 0.16);
  vertical-align: 0.05em;
}

/* --- Note types: colors from frontmatter cssclasses ---------------------- */
${noteAccentVars}

.markdown-rendered:is(${topicReading}) h1,
.markdown-source-view:is(${topicReading}) .cm-header-1 {
  color: color-mix(in srgb, var(--note-accent) 62%, var(--text-normal));
}
.markdown-rendered:is(${topicReading}) h1 {
  border-bottom: 2px solid rgba(var(--note-accent-rgb), 0.42);
  padding-bottom: 0.35em;
}

.markdown-rendered:is(${topicReading}) h2 {
  border-left: 4px solid var(--note-accent);
  border-radius: 6px;
  padding: 0.38em 0.62em;
  background: rgba(var(--note-accent-rgb), 0.11);
}
.markdown-source-view:is(${topicReading}) .HyperMD-header-2 {
  border-left: 4px solid var(--note-accent);
  border-radius: 6px;
  padding-left: 0.62em;
  background: rgba(var(--note-accent-rgb), 0.1);
}

.markdown-rendered:is(${topicReading}) h3,
.markdown-source-view:is(${topicReading}) .cm-header-3 {
  color: color-mix(in srgb, var(--note-accent) 76%, var(--text-normal));
}

.markdown-rendered:is(${topicReading}) strong,
.markdown-source-view:is(${topicReading}) .cm-strong {
  color: color-mix(in srgb, var(--note-accent) 70%, var(--text-normal));
}

.markdown-rendered:is(${topicReading}) .tag {
  border: 1px solid rgba(var(--note-accent-rgb), 0.42);
  background: rgba(var(--note-accent-rgb), 0.1);
  color: color-mix(in srgb, var(--note-accent) 72%, var(--text-normal));
}

.markdown-rendered:is(${topicReading}) th {
  background: rgba(var(--note-accent-rgb), 0.12);
  color: color-mix(in srgb, var(--note-accent) 68%, var(--text-normal));
}

.markdown-rendered:is(${topicReading}) blockquote {
  border-left-color: var(--note-accent);
  background: rgba(var(--note-accent-rgb), 0.08);
  border-radius: 0 6px 6px 0;
}

.markdown-rendered:is(${topicReading}) code {
  border-color: rgba(var(--note-accent-rgb), 0.28);
}
`;
}

// Add the snippet to appearance.json's enabled list without touching other prefs.
export function mergeAppearance(existing, snippetName = SNIPPET_NAME) {
  const a = existing && typeof existing === 'object' ? { ...existing } : {};
  const set = new Set(Array.isArray(a.enabledCssSnippets) ? a.enabledCssSnippets : []);
  set.add(snippetName);
  a.enabledCssSnippets = [...set];
  return a;
}

// Graph color groups: one per note folder, colored from the palette.
export function graphColorGroups(loc = PT) {
  return Object.values(NOTE_TYPES).map((v) => ({
    query: `path:"${loc.folders[v.folderKey]}"`,
    color: { a: 1, rgb: parseInt(PALETTE[v.palette].hex.slice(1), 16) },
  }));
}

// Merge color groups into graph.json, deduping by query and keeping other keys.
export function mergeGraphColorGroups(existing, groups) {
  const g = existing && typeof existing === 'object' ? { ...existing } : {};
  const current = Array.isArray(g.colorGroups) ? [...g.colorGroups] : [];
  const seen = new Set(current.map((x) => x.query));
  for (const group of groups) {
    if (!seen.has(group.query)) {
      current.push(group);
      seen.add(group.query);
    }
  }
  g.colorGroups = current;
  return g;
}
