// Generated Obsidian Bases + a Dashboard MOC — the vault's structural index (0.23.0).
// Each taxonomy folder gets a folder-filtered `.base` (NOT tag-filtered: a tag filter hid ~1/3
// of the corpus in production) and 00-Dashboard.md embeds them. Locale-aware; non-destructive
// (never overwrites a user's own base) unless force is passed. Zero runtime deps.
import { existsSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, resolve } from 'node:path';
import { getLocale } from '../hooks/locale.mjs';

// Per-area view: which folder, which frontmatter columns, and their display labels.
function areaSpecs(loc) {
  const f = loc.folders;
  const en = loc.id === 'en';
  const date = en ? 'Date' : 'Data';
  return [
    { key: 'sessoes', folder: f.sessions, title: en ? 'Sessions' : 'Sessões',
      cols: ['date', 'provider', 'custo_modelo_usd', 'prompts', 'tool_calls'],
      labels: { date, provider: en ? 'Agent' : 'Agente', custo_modelo_usd: 'US$', prompts: 'Prompts', tool_calls: 'Tools' } },
    { key: 'decisoes', folder: f.decisions, title: en ? 'Decisions' : 'Decisões',
      cols: ['date', 'status'], labels: { date, status: 'Status' } },
    { key: 'bugs', folder: f.bugs, title: 'Bugs',
      cols: ['date', 'status', 'severity'], labels: { date, status: 'Status', severity: en ? 'Severity' : 'Severidade' } },
    { key: 'aprendizados', folder: f.learnings, title: en ? 'Learnings' : 'Aprendizados',
      cols: ['date'], labels: { date } },
    { key: 'specs', folder: f.specs, title: 'Specs', cols: ['date'], labels: { date } },
    { key: 'mudancas', folder: f.changes, title: en ? 'Changes' : 'Mudanças',
      cols: ['date', 'status'], labels: { date, status: 'Status' } },
  ];
}

// A minimal, valid Base: folder filter + one table view. No formulas (that's where Base syntax
// errors hide) — the folder filter is the whole fix.
export function renderBase(spec) {
  const props = spec.cols.map((c) => `  ${c}:\n    displayName: ${spec.labels[c] || c}`).join('\n');
  const order = ['file.name', ...spec.cols].map((c) => `      - ${c}`).join('\n');
  return `filters:
  and:
    - file.inFolder("${spec.folder}")
    - file.ext == "md"
properties:
${props}
views:
  - type: table
    name: ${spec.title}
    order:
${order}
`;
}

export function renderDashboard(specs, en) {
  const blocks = specs.map((s) => `## ${s.title}\n\n![[${s.key}.base]]`).join('\n\n---\n\n');
  return `---
tags:
  - dashboard
cssclasses:
  - topic-dashboard
---

# ${en ? 'Vault — Overview' : 'Vault — Visão Geral'}

> ${en ? 'Generated by wendkeep. Each section embeds a folder-filtered Base view (needs the Obsidian Bases core plugin).' : 'Gerado pelo wendkeep. Cada seção embeda uma view Base filtrada por pasta (requer o core plugin Bases do Obsidian).'}

---

${blocks}
`;
}

// Write one `<key>.base` per area + 00-Dashboard.md. Non-destructive unless force. Returns the
// list of files written.
export function seedVaultViews(vaultBase, { force = false } = {}) {
  const loc = getLocale(vaultBase);
  const specs = areaSpecs(loc);
  const written = [];
  for (const s of specs) {
    const p = join(vaultBase, `${s.key}.base`);
    if (force || !existsSync(p)) { writeFileSync(p, renderBase(s), 'utf8'); written.push(`${s.key}.base`); }
  }
  const dash = join(vaultBase, '00-Dashboard.md');
  if (force || !existsSync(dash)) { writeFileSync(dash, renderDashboard(specs, loc.id === 'en'), 'utf8'); written.push('00-Dashboard.md'); }
  return written;
}

function opt(argv, name) {
  const i = argv.indexOf(name);
  if (i >= 0) return argv[i + 1];
  const eq = argv.find((a) => a.startsWith(`${name}=`));
  return eq ? eq.slice(name.length + 1) : undefined;
}

// `wendkeep dashboard [--vault P] [--force]` — (re)generate the Bases + Dashboard.
export function runDashboard(argv) {
  const vaultRaw = opt(argv, '--vault') || process.env.OBSIDIAN_VAULT_PATH;
  if (!vaultRaw) { process.stderr.write('wendkeep dashboard: no vault (--vault or OBSIDIAN_VAULT_PATH).\n'); process.exit(2); }
  const vaultBase = isAbsolute(vaultRaw) ? vaultRaw : resolve(process.cwd(), vaultRaw);
  if (!existsSync(vaultBase)) { process.stderr.write(`wendkeep dashboard: vault not found: ${vaultBase}\n`); process.exit(2); }
  const written = seedVaultViews(vaultBase, { force: argv.includes('--force') });
  process.stdout.write(written.length ? `dashboard: ${written.length} arquivo(s) — ${written.join(', ')}\n` : 'dashboard: nada a fazer (use --force para regenerar)\n');
  process.exit(0);
}
